### ISSUE TITLE
mkdocstrings should parse return type from annotation (not docstring)

### ISSUE THREAD

**Issue by billbrod** [flatironinstitute/generalized-linear-models#27]
It seems that `mkdocstrings` is unable to pick up the return type directly from the annotation for our code, and I'm unsure why, since this is supported (see https://github.com/mkdocstrings/python/issues/57#issuecomment-1409143157). Running `griffe` (the underlying parser) on the code with and without the type annotation yields identical outputs, so I'm not sure why that would be, but haven't been able to figure it out.

**Comment by pawamoy** [comment]
Do you mean that you also write the type in the docstring? Griffe gives precedence to the types written in the docstring. This was asked by users who want to "override" the type annotation with something more readable for their users. If you want Griffe to use the type annotation (from the signature), then you should remove the type from the docstring.

**Comment by billbrod** [comment]
Thanks for commenting! It looks like mkdocstrings is not extracting the return type from the type annotation if there's nothing in the docstring (argument types are fine). For example, the return type of `__mul__` is set as `Basis` in the [type annotation](https://github.com/flatironinstitute/generalized-linear-models/blob/new_basis/src/neurostatslib/basis.py#L271), but [mkdocstrings isn't grabbing it](https://generalized-linear-models--23.org.readthedocs.build/en/23/reference/neurostatslib/basis/#neurostatslib.basis.Basis.__mul__) (that's in our readthedocs, but we've also reproduced it locally). If you look at `__add__` (right above it in both locations), you can see the mkdocstrings is getting the type when it's annotated in the docstring.

I assume this is a configuration issue somewhere, but we haven't managed to track it down.

**Comment by pawamoy** [comment]
Ah you're using the Numpystyle, OK. In fact the way you write the Returns section is not supported by the Numpydoc specification/guide. We had a contribution to the docstrings parser that makes it possible though (and we're chatting with the Numpydoc maintainers). Look at the syntax described here: https://github.com/mkdocstrings/griffe/issues/173. Both the "new cases" are now supported. That means you can write your Returns section like this:

```
Returns
-------
:
    The resulting Basis object.
```

This is not particularly elegant, but we did our best to fit within the existing Numpydoc guide :slightly_smiling_face:

**Comment by billbrod** [comment]
Ah that's excellent, thanks! For some reason, I thought the proper syntax was to not include the colon if you weren't doing type annotation for numpydoc. And I confirmed that either the syntax you specified or 

```
Returns
-----------
new_basis :
    The resulting basis object.
```

will result in mkdocstrings getting the type from the annotation, so I'm closing this.

**Comment by pawamoy** [comment]
Maybe Sphinx supports the syntax you had before? I wouldn't know as I don't use Sphinx nor Numpystyle docstrings :sweat_smile:

**Comment by billbrod** [comment]
that is totally possible! I've previously (on a different project) used Sphinx, so that might be why I thought it would work.

**Comment by pawamoy** [comment]
I see, thanks, that's interesting. We should probably coordinate efforts and try not to diverge too much in our implementations of the Numpydoc guide :slightly_smiling_face:

**Comment by billbrod** [comment]
Actually, it looks like I just hadn't checked carefully enough, and the Sphinx parser I was using there wasn't grabbing the return type with that syntax either. So that's my bad!
