### ISSUE TITLE
Look into abstract classes/methods

### ISSUE THREAD

**Issue by billbrod** [flatironinstitute/generalized-linear-models#6]
I thought using `abc` decorators and classes would prevent people from instantiating the generic `Basis` class (and we should make it so it's not available under `nsl.basis`) and would require the `gen_basis_funcs` to be implemented in any subclass, but that doesn't seem to be the case. Look into why that is.

**Comment by BalzaniEdoardo** [comment]
solved, one need an abstract class with an abstract method, then the expected behavior is matched
